name: "Podcast Generator"
author: "Joe Doe"
description: "Generate a podcast feed from a directory of audio files 1"
runs:
  using: "docker"
  main: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The committer's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}